---
- name: for testing purpose
  hosts: localhost
  vars_files:
    - var.yaml  # Include variables from this file
  tasks:
    - name: printing the variables
      ansible.builtin.debug:
        msg: "my name is {{ name }} and my age is {{ age }}"
